""" removed Organiser table

Revision ID: 01045b1b750b
Revises: 89aab3bce95a
Create Date: 2025-11-07 01:41:25.728047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01045b1b750b'
down_revision: Union[str, Sequence[str], None] = '89aab3bce95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Drop the foreign key constraints FIRST
    op.drop_constraint(op.f('organiser_events_organiser_id_fkey'), 'organiser_events', type_='foreignkey')
    op.drop_constraint(op.f('users_organiser_id_fkey'), 'users', type_='foreignkey')

    # 2. NOW it's safe to drop the table
    op.drop_table('organisers')

    # 3. Proceed with the rest of the changes
    op.add_column('organiser_events', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'organiser_events', 'users', ['user_id'], ['user_id'])
    op.drop_column('organiser_events', 'organiser_id')

    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=False))
    op.add_column('users', sa.Column('phone', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('role', sa.Enum('Admin', 'Coordinator', 'Event Head', 'Volunteer', name='role_enum'), nullable=False))
    op.drop_column('users', 'organiser_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Re-create the 'organisers' table FIRST
    op.create_table('organisers',
    sa.Column('organiser_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('Admin', 'Coordinator', 'Event Head', 'Volunteer', name='role_enum'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('organiser_id', name=op.f('organisers_pkey'))
    )

    # 2. Modify the 'users' table and add its foreign key
    op.add_column('users', sa.Column('organiser_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('users_organiser_id_fkey'), 'users', 'organisers', ['organiser_id'], ['organiser_id'])
    op.drop_column('users', 'role')
    op.drop_column('users', 'email')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'name')

    # 3. Modify the 'organiser_events' table and add its foreign key
    op.add_column('organiser_events', sa.Column('organiser_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organiser_events', type_='foreignkey')
    op.create_foreign_key(op.f('organiser_events_organiser_id_fkey'), 'organiser_events', 'organisers', ['organiser_id'], ['organiser_id'])
    op.drop_column('organiser_events', 'user_id')
    
    # ### end Alembic commands ###
