"""create organiser, organise event, user table

Revision ID: 125049a5341e
Revises: 0e76745d07b6
Create Date: 2025-11-04 00:51:07.868471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '125049a5341e'
down_revision: Union[str, Sequence[str], None] = '0e76745d07b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisers',
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('role', sa.Enum('Admin', 'Coordinator', 'Event Head', 'Volunteer', name='role_enum'), nullable=False),
    sa.PrimaryKeyConstraint('organiser_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organiser_id'], ['organisers.organiser_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('organiser_events',
    sa.Column('organiser_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['organiser_id'], ['organisers.organiser_id'], ),
    sa.PrimaryKeyConstraint('organiser_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organiser_events')
    op.drop_table('users')
    op.drop_table('organisers')
    # ### end Alembic commands ###
