"""added team_event table and removed event-id from team table 

Revision ID: 23ced9ca8726
Revises: ab8a9af7853b
Create Date: 2025-11-07 21:05:44.631956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23ced9ca8726'
down_revision: Union[str, Sequence[str], None] = 'ab8a9af7853b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_events',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], ),
    sa.PrimaryKeyConstraint('team_id', 'event_id')
    )
    op.drop_constraint(op.f('teams_event_id_fkey'), 'teams', type_='foreignkey')
    op.drop_column('teams', 'event_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('teams_event_id_fkey'), 'teams', 'events', ['event_id'], ['event_id'])
    op.drop_table('team_events')
    # ### end Alembic commands ###
