"""added enum in gender(room table) and in merch_size(participant table)

Revision ID: 5a4d63f84f30
Revises: d02308288aff
Create Date: 2025-11-08 00:23:49.030999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# Import the postgresql dialect
from sqlalchemy.dialects import postgresql 

# revision identifiers, used by Alembic.
revision: str = '5a4d63f84f30'
down_revision: Union[str, Sequence[str], None] = 'd02308288aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- DEFINE YOUR ENUMS HERE ---
# (I'm guessing your gender values, please correct them if they are different)
gender_enum = postgresql.ENUM('Male', 'Female', 'Other', name='gender_enum')
merch_size_enum = postgresql.ENUM('S', 'M', 'L', 'XL', 'XXL', name='merch_size_enum')


def upgrade() -> None:
    """Upgrade schema."""
    
    # --- 1. CREATE the new types first ---
    gender_enum.create(op.get_bind())
    merch_size_enum.create(op.get_bind())

    # --- 2. Now, alter the columns using the new types ---
    # (I'm guessing the old type for gender was sa.String(10))
    op.alter_column('rooms', 'gender',
               existing_type=sa.String(length=10),
               type_=gender_enum,
               existing_nullable=True,
               # Add this magic 'using' clause
               postgresql_using='gender::gender_enum')

    op.alter_column('participants', 'merch_size',
               existing_type=sa.VARCHAR(length=5),
               type_=merch_size_enum,
               existing_nullable=True,
               # Add this magic 'using' clause
               postgresql_using='merch_size::merch_size_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # --- 1. Revert the columns back to String ---
    # (The autogenerated downgrade code is probably fine, but check it)
    op.alter_column('participants', 'merch_size',
               existing_type=merch_size_enum,
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
               
    op.alter_column('rooms', 'gender',
               existing_type=gender_enum,
               type_=sa.String(length=10),
               existing_nullable=True)

    # --- 2. NOW, you can safely DROP the enum types ---
    gender_enum.drop(op.get_bind())
    merch_size_enum.drop(op.get_bind())
    # ### end Alembic commands ###