"""create merch distribution, certificate table

Revision ID: 8119225f163f
Revises: 125049a5341e
Create Date: 2025-11-04 00:58:03.822128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8119225f163f'
down_revision: Union[str, Sequence[str], None] = '125049a5341e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('certificate_id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('certificate_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.PrimaryKeyConstraint('certificate_id')
    )
    op.create_table('merch_distribution',
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('distributed', sa.Boolean(), nullable=True),
    sa.Column('time_of_distribution', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participants.participant_id'], ),
    sa.PrimaryKeyConstraint('participant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('merch_distribution')
    op.drop_table('certificates')
    # ### end Alembic commands ###
