"""Added poc_contact field to clubs with 10-digit constraint

Revision ID: 9314f2fdfb5f
Revises: 01045b1b750b
Create Date: 2025-11-07 19:24:27.469582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9314f2fdfb5f'
down_revision: Union[str, Sequence[str], None] = '01045b1b750b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('poc_contact', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'poc_contact')
    # ### end Alembic commands ###
