"""removed room_id form primary key form room reserved table

Revision ID: ab8a9af7853b
Revises: 9314f2fdfb5f
Create Date: 2025-11-07 19:41:32.646540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab8a9af7853b'
down_revision: Union[str, Sequence[str], None] = '9314f2fdfb5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
