"""Added gender in participant table

Revision ID: bd01d9ea9dcb
Revises: 5a4d63f84f30
Create Date: 2025-11-08 15:22:08.401887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd01d9ea9dcb'
down_revision: Union[str, Sequence[str], None] = '5a4d63f84f30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('gender', sa.Enum('FEMALE', 'MALE', name='gender_enum'), nullable=False))
    op.alter_column('participants', 'merch_size',
               existing_type=postgresql.ENUM('S', 'M', 'L', 'XL', 'XXL', name='merch_size_enum'),
               nullable=False)
    op.alter_column('rooms', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', name='gender_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rooms', 'gender',
               existing_type=postgresql.ENUM('Male', 'Female', name='gender_enum'),
               nullable=True)
    op.alter_column('participants', 'merch_size',
               existing_type=postgresql.ENUM('S', 'M', 'L', 'XL', 'XXL', name='merch_size_enum'),
               nullable=True)
    op.drop_column('participants', 'gender')
    # ### end Alembic commands ###
