"""create events table

Revision ID: c7a861b5c014
Revises: 46d73110c240
Create Date: 2025-11-03 21:08:01.831108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a861b5c014'
down_revision: Union[str, Sequence[str], None] = '46d73110c240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('fest_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('technical', 'cultural', 'managerial', name='category_enum'), nullable=False),
    sa.Column('venue', sa.String(length=256), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('max_team_size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fest_id'], ['fests.fest_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
