"""Added on delete cascade constraint whereever participant_id was primary key

Revision ID: d02308288aff
Revises: 23ced9ca8726
Create Date: 2025-11-08 00:45:24.721833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd02308288aff'
down_revision: Union[str, Sequence[str], None] = '23ced9ca8726'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('certificates_participant_id_fkey'), 'certificates', type_='foreignkey')
    op.create_foreign_key(None, 'certificates', 'participants', ['participant_id'], ['participant_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('merch_distribution_participant_id_fkey'), 'merch_distribution', type_='foreignkey')
    op.create_foreign_key(None, 'merch_distribution', 'participants', ['participant_id'], ['participant_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('room_reserved_participant_id_fkey'), 'room_reserved', type_='foreignkey')
    op.create_foreign_key(None, 'room_reserved', 'participants', ['participant_id'], ['participant_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'room_reserved', type_='foreignkey')
    op.create_foreign_key(op.f('room_reserved_participant_id_fkey'), 'room_reserved', 'participants', ['participant_id'], ['participant_id'])
    op.drop_constraint(None, 'merch_distribution', type_='foreignkey')
    op.create_foreign_key(op.f('merch_distribution_participant_id_fkey'), 'merch_distribution', 'participants', ['participant_id'], ['participant_id'])
    op.drop_constraint(None, 'certificates', type_='foreignkey')
    op.create_foreign_key(op.f('certificates_participant_id_fkey'), 'certificates', 'participants', ['participant_id'], ['participant_id'])
    # ### end Alembic commands ###
