"""changed club_type to category_enum

Revision ID: e4f515dfbf0b
Revises: bd01d9ea9dcb
Create Date: 2025-11-17 16:20:21.065251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f515dfbf0b'
down_revision: Union[str, Sequence[str], None] = 'bd01d9ea9dcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clubs', 'club_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('technical', 'cultural', 'managerial', name='category_enum'),
               nullable=False,
               postgresql_using='club_type::category_enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clubs', 'club_type',
               existing_type=sa.Enum('technical', 'cultural', 'managerial', name='category_enum'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               postgresql_using='club_type::text::varchar')
    # ### end Alembic commands ###
